version: '2.4'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/app/static
    depends_on:
      db:
        condition: service_healthy
    pids_limit: 1000
    cpus: 2
    mem_limit: 2G
    restart: always
    stop_grace_period: 0s


  db:
    image: postgres:15.3
    command: "postgres -c shared_buffers=256MB -c max_connections=200"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USER}
      PGDATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres:/var/lib/postgresql/data
    pids_limit: 500
    cpus: 2
    mem_limit: 2G
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/usr/share/nginx/html/static
    depends_on:
      - app
    pids_limit: 500
    cpus: 2
    mem_limit: 2G
    restart: always
    stop_grace_period: 0s