"""Initial migration.

Revision ID: 443e3be9fa76
Revises: 
Create Date: 2024-05-18 00:34:04.000592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443e3be9fa76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('birth_year', sa.String(length=10), nullable=True),
    sa.Column('document_series', sa.String(length=10), nullable=True),
    sa.Column('document_number', sa.String(length=10), nullable=True),
    sa.Column('issue_date', sa.String(length=20), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('seal_decryption', sa.String(length=200), nullable=True),
    sa.Column('awards_information', sa.String(length=200), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.String(length=20), nullable=True),
    sa.Column('dismissal_date', sa.String(length=20), nullable=True),
    sa.Column('seal_decryption', sa.String(length=200), nullable=True),
    sa.Column('position_decryption', sa.String(length=200), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_information')
    op.drop_table('awards')
    op.drop_table('employees')
    # ### end Alembic commands ###
