"""Rename columns

Revision ID: 74aa151e2156
Revises: 443e3be9fa76
Create Date: 2024-05-18 01:16:58.872366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74aa151e2156'
down_revision = '443e3be9fa76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=100), nullable=True))
        batch_op.drop_column('order')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('document_issue_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('document_issuer', sa.String(length=200), nullable=True))
        batch_op.drop_column('issue_date')
        batch_op.drop_column('issuer')

    with op.batch_alter_table('job_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=100), nullable=True))
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('order_number')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issue_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('document_issuer')
        batch_op.drop_column('document_issue_date')
        batch_op.drop_column('document_type')

    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
